"""empty message

Revision ID: 9e4480f35b00
Revises: 8c9ec9298080
Create Date: 2019-11-14 07:04:19.369034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4480f35b00'
down_revision = '8c9ec9298080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Below is a pattern to add a column to a table that should be Nullable=False
    # When you add the column all values will be null and an error will be generated
    # on upgrade
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')

    op.alter_column('todos', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
